version: "3.4"

services:
    manh-postgres:
        image: postgres:13.1
        container_name: manh-postgres
        restart: always
        ports: 
            - "5435:5432"
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres